"""Owned hosting for micro-app products: one subdomain per product.

Deliberately small. A registry file maps `slug -> {port, directory, token}`;
a supervisor starts each app on its assigned port; the reverse proxy (nginx
config emitted here) maps `<slug>.<app_domain>` to that port. No PaaS, no
per-product manual step.

The registry is a file rather than a table because the supervisor and the
reverse proxy need to read it without a database connection — including during
a deploy where the database may be mid-migration.
"""

from __future__ import annotations

import json
import os
import signal
import socket
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from ..config import settings

_PORT_BASE = 43000


@dataclass
class Deployment:
    slug: str
    directory: str
    port: int
    hostname: str
    url: str
    auth_token: str | None = None
    pid: int | None = None


def _registry_path() -> Path:
    return settings().apps_dir / "registry.json"


def _load() -> dict[str, dict[str, Any]]:
    path = _registry_path()
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _save(registry: dict[str, dict[str, Any]]) -> None:
    path = _registry_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(registry, indent=2), encoding="utf-8")
    tmp.replace(path)  # atomic — the proxy may be reading this


def _assign_port(registry: dict[str, dict[str, Any]], slug: str) -> int:
    """Stable per slug: a redeploy keeps the same port so the proxy config
    doesn't have to change."""
    if slug in registry:
        return int(registry[slug]["port"])
    used = {int(entry["port"]) for entry in registry.values()}
    port = _PORT_BASE
    while port in used or _in_use(port):
        port += 1
    return port


def _in_use(port: int) -> bool:
    with socket.socket() as sock:
        return sock.connect_ex(("127.0.0.1", port)) == 0


def deploy(
    *, slug: str, app_dir: Path, auth_token: str | None = None, start: bool = True
) -> Deployment:
    cfg = settings()
    registry = _load()
    port = _assign_port(registry, slug)
    hostname = f"{slug}.{cfg.app_domain}"
    scheme = "https" if not cfg.app_domain.endswith("localhost") else "http"
    record = Deployment(
        slug=slug,
        directory=str(app_dir),
        port=port,
        hostname=hostname,
        url=f"{scheme}://{hostname}",
        auth_token=auth_token,
    )
    if start:
        record.pid = _start(app_dir, port)
    registry[slug] = asdict(record)
    _save(registry)
    _write_proxy_config(registry)
    return record


def _start(app_dir: Path, port: int) -> int:
    proc = subprocess.Popen(  # noqa: S603 - our own generated entrypoint
        [sys.executable, "app.py"],
        cwd=str(app_dir),
        env={"PORT": str(port), "PATH": os.environ.get("PATH", "/usr/bin:/bin")},
        stdout=(app_dir / "app.log").open("ab"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    # Give it a moment to bind; a process that exits instantly is a failed
    # deploy, not a running one.
    time.sleep(0.8)
    if proc.poll() is not None:
        raise RuntimeError(
            f"app for {app_dir.name} exited immediately; see {app_dir / 'app.log'}"
        )
    return proc.pid


def stop(slug: str) -> bool:
    registry = _load()
    entry = registry.get(slug)
    if not entry or not entry.get("pid"):
        return False
    try:
        os.killpg(os.getpgid(int(entry["pid"])), signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        return False
    entry["pid"] = None
    _save(registry)
    return True


def status() -> list[Deployment]:
    return [Deployment(**entry) for entry in _load().values()]


def _write_proxy_config(registry: dict[str, dict[str, Any]]) -> None:
    lines = [
        "# Generated by Product Factory — do not edit by hand.",
        "# Reload nginx after a deploy: nginx -s reload",
        "",
    ]
    for entry in registry.values():
        lines += [
            "server {",
            "    listen 80;",
            f"    server_name {entry['hostname']};",
            "    location / {",
            f"        proxy_pass http://127.0.0.1:{entry['port']};",
            "        proxy_set_header Host $host;",
            "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
            "        proxy_set_header X-Forwarded-Proto $scheme;",
            "    }",
            "}",
            "",
        ]
    (settings().apps_dir / "nginx.conf").write_text("\n".join(lines), encoding="utf-8")
